### PR TITLE
Found incompatible Titanium Modules in Ti SDK 6.0.0.GA 

### PR DESCRIPTION
**Pull request by csemrm**
Found incompatible Titanium Modules in Ti SDK 6.0.0.GA  fixed by doing GCM liberty changes

### CODE REVIEW

**Comment by DouglasHennrich** [comment]
Can you upload a dist file so we can download it ? Thanks @csemrm

**Comment by ErikDohmen-xx** [comment]
@csemrm yes please do so as it seems that @arleyandrada hasn't been around for a while (hasn't been active in two months now).

**Comment by ErikDohmen-xx** [comment]
@csemrm Could you? Thanks!
@DouglasHennrich did you get any step further?

**Comment by ErikDohmen-xx** [comment]
@arleyandrada Thanks!!!
Could you make a distribution file as well in order to get things running.

**Comment by arleyandrada** [comment]
@ErikDohmen https://github.com/arleyandrada/PushClient/blob/master/dist/br.com.arlsoft.pushclient-android-1.21.zip

**Comment by arleyandrada** [comment]
I am unable to perform tests, however I am releasing the new version based on what was sent by @csemrm 

My free developer account was rejected by the Appcelerator team and I don't want to pay for a new account.

**Pull request merged**
